### ISSUE TITLE
OpenVPN ami no longer available

### ISSUE THREAD

**Issue by chadgrant** [hashicorp/best-practices#47]
* aws_instance.openvpn: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit http://aws.amazon.com/marketplace/pp?sku=5dqgmcl3euukqlclj1x3ecbav

When I go to Opt In or Accept the EULA. It says the AMI is no longer available.

I may be using the wrong AMI?

**Comment by bensojona** [comment]
@chadgrant can you try using `ami-6fef5804` and see if that one works? 

You'll just need to replace the [`openvpn_ami` variable](https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/us_east_1_staging/terraform.tfvars#L50) in the terraform.tfvars file(s) and in the Variables section of Atlas.

**Comment by bensojona** [comment]
@chadgrant also, were you using [`ami-5fe36434`](https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/us_east_1_staging/terraform.tfvars#L50)? 

The [link](https://aws.amazon.com/marketplace/pp?sku=5dqgmcl3euukqlclj1x3ecbav) given brings me to `Version: 2.0.8` of the appliance, however, `ami-5fe36434` (version provided in the repo) is [`Version: 2.0.20`](https://aws.amazon.com/marketplace/pp/B00MI40CAE/ref=sp_mpg_product_title?ie=UTF8&sr=0-2), which should be available. It worked just fine when I've used it, as recent as last week.

**Comment by chadgrant** [comment]
I think the problem is me using US-West-2. The latest pvm they have is 2.0.8, ami-13c1bc23 (at least as far as I can tell)

**Comment by bensojona** [comment]
Ahh, I see. `ami-9fe2f2af` or `ami-9de9fcad` both worked for me in US-West-2, but they were hvm. 

Looks like OpenVPN hasn't been supporting pvm with their more recent versions of the appliance, is that a hard requirement?

**Comment by chadgrant** [comment]
It was my fault, I was mismatching instance-types and visualization types. I'm using ami-9fe2f2af with a t2.small

But now I can't seem to get the provisioning to work.

module.network.openvpn.aws_instance.openvpn (remote-exec): Using configured bastion host...
module.network.openvpn.aws_instance.openvpn (remote-exec):   Host: 52.33.113.209
module.network.openvpn.aws_instance.openvpn (remote-exec):   User: ubuntu
module.network.openvpn.aws_instance.openvpn (remote-exec):   Password: false
module.network.openvpn.aws_instance.openvpn (remote-exec):   Private key: true
module.network.openvpn.aws_instance.openvpn (remote-exec):   SSH Agent: false
module.network.openvpn.aws_instance.openvpn (remote-exec): Connecting to remote host via SSH...
module.network.openvpn.aws_instance.openvpn (remote-exec):   Host: 10.99.99.43
module.network.openvpn.aws_instance.openvpn (remote-exec):   User: ubuntu
module.network.openvpn.aws_instance.openvpn (remote-exec):   Password: false
module.network.openvpn.aws_instance.openvpn (remote-exec):   Private key: true
module.network.openvpn.aws_instance.openvpn (remote-exec):   SSH Agent: false
module.network.openvpn.aws_instance.openvpn (remote-exec): Using configured bastion host...
module.network.openvpn.aws_instance.openvpn (remote-exec):   Host: 52.33.113.209
module.network.openvpn.aws_instance.openvpn (remote-exec):   User: ubuntu
module.network.openvpn.aws_instance.openvpn (remote-exec):   Password: false
module.network.openvpn.aws_instance.openvpn (remote-exec):   Private key: true
module.network.openvpn.aws_instance.openvpn (remote-exec):   SSH Agent: false
Error applying plan:

1 error(s) occurred:

* ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain


I can get into the bastion and ping the openvpn server. That's as far as I've gotten.

**Comment by bensojona** [comment]
Have you updated the Terraform variables in Atlas that have the values REPLACE_IN_ATLAS with the key contents used to generate the key pair?

Terraform uses the private key in that variable to ssh in for the remote-exec provisioner.

**Comment by chadgrant** [comment]
I have not gotten to Atlas yet, just been learning Terraform. I am just using the modules/network/* currently.

I generated the openvpn crt/key files with easy-rsa and am using my aws key pair.

I know my key pair is working for aws and I have seen the remote-exec connect and attempt to setup openvpn (when I was debugging with a bare ubuntu ami). The ubuntu ami remote-exec failed obviously because it didn't have openvpn on it, but it did connect and try. Kinda at a loss why it doesn't want to connect to the openvpn ami.

**Comment by bensojona** [comment]
@chadgrant yep, the `openvpnas` username was passed in [here](https://github.com/hashicorp/best-practices/blob/master/terraform/modules/aws/network/openvpn/main.tf#L76) from [terraform.tfvars](https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/us_east_1_staging/terraform.tfvars#L51).

Another thing to make sure is set is the `admin_user` ([`vpnadmin`](https://github.com/hashicorp/best-practices/blob/master/terraform/providers/aws/us_east_1_staging/terraform.tfvars#L52)) and `admin_pw` (whatever you want)  in [user_data](https://github.com/hashicorp/best-practices/blob/master/terraform/modules/aws/network/openvpn/main.tf#L69-L72) per the [OpenVPN instructions](https://docs.openvpn.net/how-to-tutorialsguides/virtual-platforms/amazon-ec2-appliance-ami-quick-start-guide/).

Odd that you couldn't get `ami-9fe2f2af` in US-West-2 to work, it performed the remote exec just fine using a t2.micro instance when I did it in US-West-2.

I haven't come across the error you received before either, which version of Terraform are you using? Passing the private key contents into `key_file` rather than a file path was new in 0.6.7. Can you share your config? 

That looks more like an issue with the AMI (or maybe the `user_data` wasn't properly passed in) as it's unable to successfully fun the remote-exec commands that seem to work just fine on other AMI's.

![image](https://cloud.githubusercontent.com/assets/2430570/11493835/46a90290-97c2-11e5-93fd-8a52162a5dc8.png)

**Comment by kwent** [comment]
Hi,

I also got 

```
module.network.openvpn.aws_instance.openvpn (remote-exec): SSH Agent: false
module.network.openvpn.aws_instance.openvpn (remote-exec): Connected!
module.network.openvpn.aws_instance.openvpn (remote-exec): ERROR: [Errno 2] No such file or directory: 'out/tmp-BuPKd3z5jCfO.tmp': util/options:79,sagent/sacli:295,util/file:142,util/file:137,util/file:130,util/simplefile:11 (exceptions.IOError)
module.network.openvpn.aws_instance.openvpn (remote-exec): ERROR: [Errno 2] No such file or directory: 'out/tmp-zDs4TAH6BkA9.tmp': util/options:79,sagent/sacli:295,util/file:142,util/file:137,util/file:130,util/simplefile:11 (exceptions.IOError)
module.network.openvpn.aws_instance.openvpn (remote-exec): ERROR: [Errno 2] No such file or directory: 'out/tmp-VdNFAVYE4mWg.tmp': util/options:79,sagent/sacli:295,util/file:142,util/file:137,util/file:130,util/simplefile:11 (exceptions.IOError)
```

I added a `sleep 60` before those [lines](https://github.com/hashicorp/best-practices/blob/master/terraform/modules/aws/network/openvpn/openvpn.tf#L88) to let openvpn time to set up everything.
