### ISSUE TITLE
NAT iptables rules are not persisted across reboots

### ISSUE THREAD

**Issue by clstokes** [hashicorp/best-practices#67]
If the NAT instance reboots (purposefully or not), the iptables rules are not reloaded so the NAT function fails and all instances behind the NAT fail. 

The iptables rules should be persisted across reboots.

**Comment by laferrieren** [comment]
Best practices as I understand it now are to use a nat gateway now, as it is HA by default and managed by amazon.  It would eliminate the iptables issues. Terraform also supports it now.
https://www.terraform.io/docs/providers/aws/r/nat_gateway.html
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-comparison.html

Would be happy to take a swing at converting over to using the gateway instead of a nat box.
