### ISSUE TITLE
Monthly cost for this infrastructure on AWS

### ISSUE THREAD

**Issue by faun** [hashicorp/best-practices#94]
According to some back of the napkin calculations, this setup appears to run about $166 per month. If paid upfront for 3 years with reserved instances: $106.79 per month. Does this sound about right to you?

**Comment by clstokes** [comment]
@faun last we measured, it was close to $300 for on-demand instances, so that for reserved instances sounds about right.

You can trim some costs by changing some of the instance types to t2.nano's and only setup staging **or** prod, if needed.

**Comment by jamesdaniels** [comment]
It's not the costs on AWS that will get you, but Hashicorp's services. They start @ $2k/year/seat as I just found out. Really fucked myself by baking this into my side projects.

**Comment by mitchellh** [comment]
@jamesdaniels Using Terraform on its own is completely free and we never intend for Terraform usage (or any of our other open source even) to ever _require_ anyone to buy up. We have tens of thousands of active TF users that will never be Enterprise customers and that is okay! 

So yes, you can say our enterprise Terraform offering at the time of posting starts at $2k/year/seat which is correct, but **using Terraform is completely free** except for the infrastructure costs incurred, which @clstokes answered above.

I don't want anyone to become confused by this because it is important: our open source tools are completely free in every way. We have enterprise tooling above it which is commercial.

**Comment by jamesdaniels** [comment]
At least the last I made any significant changes to my personal projects infra, using this repo as my base, Atlas seemed the best way to automate Packer and Terraform and keep it from blowing up our infra randomly (whilst automated). To suddenly have a sales throw me a number like this, after being a beta tester, locking us out from deploying new releases, was a bit shocking, and since Atlas's price is listed nowhere (and is pushed as a best practice [at least last time I looked])--I think this stands as a fair critique.

This infra, in it's most stable and automated form; will cost you a great deal more than $xyz per month.

Mitchell has recently reached out and I will be making some time with him to look at this. Perhaps the new Terraform doesn't randomly blow up your infra w/o Atlas now... perhaps next release. IDK

**Comment by jamesdaniels** [comment]
And yeah, I was freaking out a bit after I got locked out + a number like that was thrown at me. So I might be being unfair here.

**Comment by mitchellh** [comment]
I can promise you that Terraform Enterprise does not "randomly blow up your infra w/o Atlas". 

It sounds like you feel that Atlas provides the only way for you to not "randomly blow up your infra." This is what I messaged you about getting in touch with me because this _must_ be possible without Atlas. It must be. Its a prime directive of Terraform and its something you must not have to pay for. 

This infrastructure will only cost you a few hundred dollars per month. Terraform will not "randomly blow up your infra" even if you don't pay us. I understand you've been hitting these issues and we'll talk about that but the great, great majority of people (including enterprise customers that DON'T PAY US and use Terraform for thousands of resources) do not have any issues with "randomly blow[ing] up your infra."

During the beta and up to today, we were still in a period of price exploration and market segment exploration. This is the part that I'm sorry we didn't communicate better and openly admit a mistake to. We've had a lot of success targeting the enterprise market segment at the price points now quoted to you (starting at $2K/user/seat), and this is the sales/marketing/support/business motion we're now building around to sustain our open source projects and company as a whole.

You were -- I admit -- a victim of this uncertainly. And as I said before, I'm sorry this wasn't better communicated. We've talked about it internally and will do better.

One thing I've made clear from _day one_ of commercialization in any form is that our open source must stand alone. You must never be forced into an enterprise purchase to get the primary value out of the project. For example: we must not compromise security with Vault behind a paywall. We can't charge for security for Vault.

With Terraform, we follow a similar principle and tens of thousands of unique users use Terraform succesfully without paying us. We don't expect them to pay us and that's okay.

We're about to ship a major feature release (0.8) that ships all 100% open, free features. We also are planning a 0.9 release that focuses on improving state safety _without_ the use of Atlas. We've always supported remote state targets that aren't our enterprise offering so that you aren't forced into Atlas for state safety: you could easily sends it to S3 with versioning and just roll back. 

Atlas (Terraform Enterprise) is meant to be the easiest way to get collaboration benefits with Terraform: approvals, ACLs, run history, remote plan/apply, etc. None of this compromises on the prime ability for Terraform to _create and maintain infrastructure_, which is and always will be completely free.

**Comment by jamesdaniels** [comment]
0.9 sounds like it will help. I believe the trouble that I originally was having in creating an automated infrastructure was concurrent builds in Travis stepping on each other. Locks would help emensely. 

I do use Terraform succesfully in several projects, but it does require supervision. That was why I enjoyed using Atlas so much. I'm upset to see it go.

I recognized some level of risk in using a beta but this was all around handled poorly; including on my side. I felt cornered by sales. Sorry for making a fuss. 

I've filed #213 and am happy to make suggestions there.

**Comment by bensojona** [comment]
@jamesdaniels added a note in #222 to make it more clear that Atlas is optional at the beginning, please comment or PR with additional suggestions.

[Terraform 0.9](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#090-march-15-2017) introduced additional backend types that offer [state locking](https://www.terraform.io/docs/backends/state.html), which should resolve requiring Atlas for that functionality as you can now use Local, S3 (via DynamoDB), and Consul backend types.
